# Generated by Django 2.0.7 on 2018-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
                migrations.CreateModel(
            name='logement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Television', models.BooleanField()),
                ('Douche', models.BooleanField()),
                ('Hammam', models.BooleanField()),
                ('Baignoire', models.BooleanField()),
                ('Seche_cheveux', models.BooleanField()),
                ('Balcon', models.BooleanField()),
                ('Terrasse', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Climatisation', models.BooleanField()),
                ('Wifi', models.BooleanField()),
                ('Jacuzzi', models.BooleanField()),
                ('Ascenseur', models.BooleanField()),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='logements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Television', models.BooleanField()),
                ('Douche', models.BooleanField()),
                ('Hammam', models.BooleanField()),
                ('Baignoire', models.BooleanField()),
                ('Seche_cheveux', models.BooleanField()),
                ('Balcon', models.BooleanField()),
                ('Terrasse', models.BooleanField()),
                ('Parking', models.BooleanField()),
                ('Climatisation', models.BooleanField()),
                ('Wifi', models.BooleanField()),
                ('Jacuzzi', models.BooleanField()),
                ('Ascenseur', models.BooleanField()),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Climatisation', models.BooleanField()),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='voitures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Climatisation', models.BooleanField()),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
                ]
