# Generated by Django 2.0.7 on 2018-09-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logement',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='vehicule',
        ),
    ]
