# Generated by Django 2.0.7 on 2018-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0002_auto_20180903_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Photo1', models.ImageField(upload_to='')),
                ('Photo2', models.ImageField(upload_to='')),
                ('Photo3', models.ImageField(upload_to='')),
                ('Presentation', models.TextField()),
            ],
        ),
    ]
