# Generated by Django 2.0.7 on 2018-09-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0003_res'),
    ]

    operations = [
        migrations.DeleteModel(
            name='res',
        ),
    ]
