# Generated by Django 2.0.7 on 2018-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc', '0004_delete_res'),
    ]

    operations = [
        migrations.CreateModel(
            name='res',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('prénom', models.CharField(max_length=30)),
                ('Adresse', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Date_Arrivée', models.DateField(max_length=30)),
                ('Date_Départ', models.DateField(max_length=30)),
            ],
        ),
    ]
